# Generated by Django 5.0 on 2023-12-28 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Password must be at least 8 characters.'), django.core.validators.RegexValidator(message='Password must contain at least one letter and one number.', regex='^(?=.*[a-zA-Z])(?=.*\\d).+$')])),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='The time the user field was created')),
                ('updatedAt', models.DateTimeField(verbose_name='The time the user field was updated')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
